
-- INSERIR FORNECEDOR
CREATE PROCEDURE PRC_INSERIRFORNECEDOR
(@P_NOME_FORNECEDOR VARCHAR(100),
@P_CNPJ_FORNECEDOR CHAR(14),
@P_ID_FORNECEDOR INT OUT
)
AS 
BEGIN
SET NOCOUNT ON

IF EXISTS 
(SELECT * FROM FORNECEDOR WHERE NOME_FORNECEDOR = @P_NOME_FORNECEDOR AND CNPJ_FORNECEDOR = @P_CNPJ_FORNECEDOR)
BEGIN 
 PRINT' FORNECEDOR JÁ EXISTE'
 SET @P_ID_FORNECEDOR= (SELECT ID_FORNECEDOR FROM FORNECEDOR WHERE NOME_FORNECEDOR = @P_NOME_FORNECEDOR AND CNPJ_FORNECEDOR = @P_CNPJ_FORNECEDOR)
 END

ELSE
BEGIN 
 INSERT INTO FORNECEDOR (NOME_FORNECEDOR, CNPJ_FORNECEDOR) VALUES (@P_NOME_FORNECEDOR, @P_CNPJ_FORNECEDOR)
 SET @P_ID_FORNECEDOR = SCOPE_IDENTITY();
 END 

 SELECT @P_ID_FORNECEDOR;
END

---------------------- INSERIR HISTORICO NOTA


CREATE PROCEDURE PRC_INSERIR_HISTORICO_NOTA
(
@P_CHAVE_NOTA VARCHAR(44),
@P_OBSERVACAO_NOTA VARCHAR(350),
@P_ID_NOTA_FISCAL INT OUT
)
AS BEGIN

DECLARE 
 -- 
@P_UF_NOTA CHAR(2)			   = (SELECT SUBSTRING(@P_CHAVE_NOTA,1,2)),
@P_ANOMES INT			   = (SELECT SUBSTRING(@P_CHAVE_NOTA,3,4)),
@P_CNPJ_EMITENTE CHAR(14)	   = (SELECT SUBSTRING(@P_CHAVE_NOTA,7,14)),
@P_MODELO_NOTA CHAR(2)		   = (SELECT SUBSTRING(@P_CHAVE_NOTA,21,2)),
@P_SERIE_NOTA CHAR(3)		   = (SELECT SUBSTRING(@P_CHAVE_NOTA,23,3)),
@P_NUMERO_NOTA INT		   = (SELECT SUBSTRING(@P_CHAVE_NOTA,26,9)),
@P_FORMA_EMISSAO_NOTA CHAR(1)  = (SELECT SUBSTRING(@P_CHAVE_NOTA,35,1))

SET NOCOUNT ON
IF EXISTS
(SELECT * FROM HISTORICO_NOTA_FISCAL WHERE CHAVE_NOTA=@P_CHAVE_NOTA)
BEGIN 
PRINT 'CHAVE DE NOTA JÁ CADASTRADA'
SET @P_ID_NOTA_FISCAL = (SELECT ID_NOTA_FISCAL FROM HISTORICO_NOTA_FISCAL WHERE CHAVE_NOTA=@P_CHAVE_NOTA)
END

ELSE
BEGIN 

INSERT INTO HISTORICO_NOTA_FISCAL (CHAVE_NOTA,UF_NOTA,ANOMES,CNPJ_EMITENTE,MODELO_NOTA,SERIE_NOTA,NUMERO_NOTA,FORMA_EMISSAO_NOTA, DATA_CADASTRO,OBSERVACAO_NOTA) 
VALUES(@P_CHAVE_NOTA, @P_UF_NOTA,@P_ANOMES,@P_CNPJ_EMITENTE,@P_MODELO_NOTA,@P_SERIE_NOTA,@P_NUMERO_NOTA,@P_FORMA_EMISSAO_NOTA,GETDATE(),@P_OBSERVACAO_NOTA)

SET @P_ID_NOTA_FISCAL = SCOPE_IDENTITY();
END

SELECT @P_ID_NOTA_FISCAL;
END



-------------------- INSERIR PRODUTO

CREATE PROCEDURE PRC_INSERIR_PRODUTO
(@P_CODIGO_PRODUTO_FORNECEDOR INT,
@P_NOME_PRODUTO VARCHAR(250),
@P_ID_FORNECEDOR INT,
@P_ID_PRODUTO INT OUT)
AS BEGIN
SET NOCOUNT ON
IF EXISTS
(SELECT * FROM PRODUTO WHERE CODIGO_PRODUTO_FORNECEDOR=@P_CODIGO_PRODUTO_FORNECEDOR AND ID_FORNECEDOR=@P_ID_FORNECEDOR)
BEGIN
-- RECEM ALTERADO
SET @P_ID_PRODUTO= (SELECT ID_PRODUTO FROM PRODUTO WHERE CODIGO_PRODUTO_FORNECEDOR=@P_CODIGO_PRODUTO_FORNECEDOR AND ID_FORNECEDOR=@P_ID_FORNECEDOR)
PRINT 'PRODUTO JÁ CADASTRADO';

END 

ELSE 
BEGIN
INSERT INTO PRODUTO (CODIGO_PRODUTO_FORNECEDOR,NOME_PRODUTO,ID_FORNECEDOR,DATA_ATUALIZACAO) VALUES(@P_CODIGO_PRODUTO_FORNECEDOR,@P_NOME_PRODUTO,@P_ID_FORNECEDOR,GETDATE());
SET @P_ID_PRODUTO = SCOPE_IDENTITY();
END
SELECT @P_ID_PRODUTO;
END


------------------ INSERINDO OS ITENS DA NOTA
CREATE PROCEDURE PRC_ITEM_NOTA_FISCAL
(
@P_ID_FORNECEDOR INT,
@P_ID_PRODUTO INT,
@P_VL_UNITARIO MONEY,
@P_QUANTIDADE DECIMAL(10,3),
@P_VL_TOTAL_ITEM MONEY,
@P_ID_NOTA_FISCAL INT,
@P_ID_ITEM_NOTA_FISCAL INT OUT

)
AS BEGIN
IF EXISTS -- verificar essa condição ,porque um mesmo item pode se repetir numa nota
(SELECT * FROM ITEM_NOTA_FISCAL WHERE (ID_NOTA_FISCAL = @P_ID_NOTA_FISCAL  AND ID_FORNECEDOR=@P_ID_FORNECEDOR AND ID_PRODUTO=@P_ID_PRODUTO AND QUANTIDADE=@P_QUANTIDADE AND VL_UNITARIO=@P_VL_UNITARIO))
BEGIN 
 SET @P_ID_ITEM_NOTA_FISCAL = (SELECT ID_ITEM_NOTA_FISCAL FROM ITEM_NOTA_FISCAL WHERE (ID_NOTA_FISCAL = @P_ID_NOTA_FISCAL  AND ID_FORNECEDOR=@P_ID_FORNECEDOR AND ID_PRODUTO=@P_ID_PRODUTO 
 AND QUANTIDADE=@P_QUANTIDADE AND VL_UNITARIO=@P_VL_UNITARIO))
PRINT 'ITEM JÁ CADASTRADA PARA ESSA NOTA'
END

ELSE

BEGIN 
INSERT INTO ITEM_NOTA_FISCAL
(ID_FORNECEDOR,ID_PRODUTO,VL_UNITARIO,QUANTIDADE,VL_TOTAL_ITEM,ID_NOTA_FISCAL) VALUES( @P_ID_FORNECEDOR, @P_ID_PRODUTO,@P_VL_UNITARIO,@P_QUANTIDADE,@P_VL_TOTAL_ITEM,@P_ID_NOTA_FISCAL)
SET @P_ID_ITEM_NOTA_FISCAL = SCOPE_IDENTITY();
END 
SELECT @P_ID_ITEM_NOTA_FISCAL;
END