CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INT IDENTITY (1,1) NOT NULL,
NOME_FORNECEDOR VARCHAR(100),
CNPJ_FORNECEDOR CHAR(14)
PRIMARY KEY (ID_FORNECEDOR)
)


CREATE TABLE HISTORICO_NOTA_FISCAL
(ID_NOTA_FISCAL INT IDENTITY (1,1) NOT NULL,
CHAVE_NOTA VARCHAR(44) NOT NULL,
UF_NOTA CHAR(2),
ANOMES INT,
CNPJ_EMITENTE CHAR(14),
MODELO_NOTA CHAR(2),
SERIE_NOTA CHAR(3),
NUMERO_NOTA INT,
FORMA_EMISSAO_NOTA CHAR(1),
DATA_CADASTRO DATETIME,
OBSERVACAO_NOTA VARCHAR(350)

PRIMARY KEY(ID_NOTA_FISCAL)
)


CREATE TABLE PRODUTO
(ID_PRODUTO INT IDENTITY(1,1) NOT NULL,
CODIGO_PRODUTO_FORNECEDOR INT NOT NULL,
NOME_PRODUTO VARCHAR(250) NOT NULL,
ID_FORNECEDOR INT NOT NULL,
DATA_ATUALIZACAO DATETIME

PRIMARY KEY(ID_PRODUTO)
)
ALTER TABLE PRODUTO  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDOR] FOREIGN KEY(ID_FORNECEDOR)
REFERENCES FORNECEDOR (ID_FORNECEDOR)


CREATE TABLE ITEM_NOTA_FISCAL
(ID_ITEM_NOTA_FISCAL INT IDENTITY(1,1) NOT NULL,
ID_FORNECEDOR INT NOT NULL,
ID_PRODUTO INT NOT NULL,
VL_UNITARIO MONEY NOT NULL,
QUANTIDADE DECIMAL(10,3) NOT NULL,
VL_TOTAL_ITEM MONEY  NOT NULL,
ID_NOTA_FISCAL INT NOT NULL

PRIMARY KEY(ID_ITEM_NOTA_FISCAL )

)
ALTER TABLE ITEM_NOTA_FISCAL  WITH CHECK ADD  CONSTRAINT [FK_ITEM_FORNECEDOR] FOREIGN KEY(ID_FORNECEDOR)
REFERENCES FORNECEDOR (ID_FORNECEDOR)

ALTER TABLE ITEM_NOTA_FISCAL  WITH CHECK ADD  CONSTRAINT [FK_ID_PRODUTO] FOREIGN KEY(ID_PRODUTO)
REFERENCES PRODUTO (ID_PRODUTO)


